version: '3.8'
services:
    stac_browser:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: stac_browser_image
        container_name: stac_browser_container
        restart: unless-stopped
        ports:
            - "8080:8080"
        command: ['npm', 'start', '--']